# NumPy  SciPy

In [1]:
import numpy as np

In [2]:
np.__version__

'1.17.2'

## Задание 1 ★★☆

Разбейте массив на убывающие подмассивы.  
Подсказка: np.diff()  
Используйте библиотеку `numpy`, не используйте циклы.

In [24]:
def function_1(arr):
    return np.split(arr, np.where( np.diff(arr) >= 0 )[0]+1)
print(function_1([3, 2, 1, 4, 5, 2, 0, 2, 4, 1]))
# 1
print( len(function_1([3, 2, 1, 4, 5, 2, 0, 2, 4, 1])) == 5 )

# 2
np.random.seed(42)
arr2 = np.random.randint(-10, 10, size=20)
#print(arr2)
#print(function_1(arr2))
print( len(function_1(arr2)) == 9 )

# 3
np.random.seed(42)
print( len(function_1(np.random.randint(-10, 100, size=10))) == 4 )

[array([3, 2, 1]), array([4]), array([5, 2, 0]), array([2]), array([4, 1])]
True
True
True


Проверка

In [3]:
function_1([3, 2, 1, 4, 5, 2, 0, 2, 4, 1])

[array([3, 2, 1]), array([4]), array([5, 2, 0]), array([2]), array([4, 1])]

In [4]:
len(function_1([3, 2, 1, 4, 5, 2, 0, 2, 4, 1])) == 5

True

In [5]:
np.random.seed(42)
len(function_1(np.random.randint(-10, 10, size=20))) == 9

True

In [6]:
np.random.seed(42)
len(function_1(np.random.randint(-10, 100, size=10))) == 4

True

Значение для формы

In [25]:
np.random.seed(21)
a = np.random.uniform(0, 3000, size=1000)
print(len(function_1(a)))

505


## Задание 2 ★★☆

Дан массив arr, необходимо найти среднее значение внутри групп, группа определена массивом g. Например, для  
`arr = [4, 2, 1, 5, 2, 5, 1, 3]` и   
`g =   [0, 1, 1, 0, 1, 0, 1, 0]` (4 относится к группе 0, 2 к группе 1 и т. д.)   
Средние по группам: `[4.25, 1.5]`  
Подсказка: `np.bincount()`   
Используйте библиотеку `numpy`, не используйте циклы.

In [48]:
def function_2(arr, g):
    tmp = np.unique(g, return_counts=True, return_inverse=True)
    g, counts1 = tmp[1], tmp[2]
    sums = np.bincount(g, weights=arr)
    counts = np.bincount(g, weights=np.ones( arr.shape ) )
    assert( all(counts == counts1) )
    return sums / counts

print(function_2(np.array([4, 2, 1, 5, 2, 5, 1, 3]), np.array([0, 2, 2, 0, 2, 0, 2, 0])) )
# 1
print( all(function_2(np.array([4, 2, 1, 5, 2, 5, 1, 3]), np.array([0, 1, 1, 0, 1, 0, 1, 0])) == [4.25, 1.5]) )
# 2
np.random.seed(42)
print( all(function_2(np.random.randint(0, 25, size=10), np.random.randint(0, 3, size=10)) == [12., 15.2, 10.]) )
# 3
np.random.seed(42)
print( all(function_2(np.random.randint(0, 100, size=10), np.random.randint(0, 4, size=10)) == [89., 78., 20., 54.]) )

[4.25 1.5 ]
True
True
True


Проверочный код

In [9]:
all(function_2(np.array([4, 2, 1, 5, 2, 5, 1, 3]), np.array([0, 1, 1, 0, 1, 0, 1, 0])) == [4.25, 1.5])

True

In [10]:
np.random.seed(42)
all(function_2(np.random.randint(0, 25, size=10), np.random.randint(0, 3, size=10)) == [12., 15.2, 10.])

True

In [11]:
np.random.seed(42)
all(function_2(np.random.randint(0, 100, size=10), np.random.randint(0, 4, size=10)) == [89., 78., 20., 54.])

True

Значение для формы

In [49]:
np.random.seed(21)
a = np.random.uniform(0, 3000, size=1000)
g = np.random.randint(0, 20, 1000)
print(np.round(function_2(a, g).sum(), 4))

30021.8043


## Задание 3 ★★★

Предположим нам даны две выборки-матрицы: обучающая X_train (размер l1 x n) и тестовая X_test (размер l2 x n), каждая строка в матрице - это вектор, описывающий объект в n-мерном пространстве. Допустим, что в ходе некоторой задачи потребовалось вычислить расстояние между векторами из тестовой и обучающей выборки. То есть для каждой строки-вектора из тестовой выборки нужно найти расстояние до каждого вектора из обучающей, таким образом мы получим матрицу dist размера l1 x l2.   

В этом задании необходимо получить матрицу расстояний dist, **не используя циклы**.
Для начала, попробуйте это сделать через два цикла и сравните эффективность с конечной реализацией через numpy.  

In [7]:
def function_3_1(X_train, X_test):
    l1, l2 = X_train.shape[0], X_test.shape[0]
    dist = np.zeros((l1, l2))
    print(dist.shape)
    for i in range(l1):
        for j in range(l2):
            dx = X_train[i] - X_test[j]
            dist[i][j] = np.sqrt( dx @ dx )
    return dist

Значение для формы

In [8]:
%%time
np.random.seed(42)
X_train, X_test = np.random.rand(60000, 3000), np.random.rand(1000, 3000)
dist = function_3_1(X_train, X_test)
print(np.round(dist.sum(), 4))

(60000, 1000)
1341747083.8534
CPU times: user 25min 40s, sys: 1min 15s, total: 26min 55s
Wall time: 30min 12s


In [11]:
def function_3_2(X_train, X_test):
    l1, l2 = X_train.shape[0], X_test.shape[0]
    train_sq = (X_train * X_train).sum(axis=1)
    test_sq = (X_test * X_test).sum(axis=1)
    dist = np.tile(train_sq.reshape(-1, 1), l2)
    dist += np.tile(test_sq, (l1, 1))
    dist -= 2 * X_train @ X_test.T
    #print(dist.shape)
    return np.sqrt(dist)

In [12]:
%%time
np.random.seed(42)
X_train, X_test = np.random.rand(60000, 3000), np.random.rand(1000, 3000)
dist2 = function_3_2(X_train, X_test)
print(np.round(dist2.sum(), 4))

1341747083.8534
CPU times: user 49.9 s, sys: 24.9 s, total: 1min 14s
Wall time: 2min 25s


In [10]:
np.all(np.isclose(dist, dist2))

True

## Задание 4 ★☆☆

Реализуйте функцию вычисляющую приближенную матрицу $X_k$  для матрицы $X$ заданного ранга $k$ по норме Фробениуса.   
Подсказка:   
см. семнар SciPy  
scipy.linalg.svd  

In [22]:
import scipy

In [37]:
from scipy.linalg import svd

X = np.random.randn(4, 3)
print(X)
U, D, V = svd(X, full_matrices=False)
print(U.shape, np.diag(D).shape, V.shape)
print(type(U), type(D), type(V))
X1 = (U * D ) @ V
print(np.allclose(X, X1))

def function_4(X, k):
    U, D, V = svd(X, full_matrices=False)
    k = min(k, D.shape[0])
    D[k:] = 0
    X_k = U * D @ V
    return X_k

np.random.seed(42)
X = np.random.randint(0, 10, size=(4, 5))
X_k = function_4(X, 3)
print(scipy.linalg.norm(X - X_k))
print(np.linalg.matrix_rank(X_k))

[[-0.46341769 -0.46572975  0.24196227]
 [-1.91328024 -1.72491783 -0.56228753]
 [-1.01283112  0.31424733 -0.90802408]
 [-1.4123037   1.46564877 -0.2257763 ]]
(4, 3) (3, 3) (3, 3)
<class 'numpy.ndarray'> <class 'numpy.ndarray'> <class 'numpy.ndarray'>
True
1.76440345368773
3


Проверка

In [38]:
np.random.seed(42)
X = np.random.randint(0, 10, size=(4, 5))
X_k = function_4(X, 3)
(scipy.linalg.norm(X - X_k) < 2 and np.linalg.matrix_rank(X_k) == 3)

True

In [39]:
np.random.seed(42)
X = np.random.randint(0, 10, size=(4, 5))
X_k = function_4(X, 4)
(scipy.linalg.norm(X - X_k) < 1e-10 and np.linalg.matrix_rank(X_k) == 4)

True

Значение для формы

In [40]:
np.random.seed(42)
X = np.random.randint(0, 10, size=(100, 150))
X_k = function_4(X, 40)
print(np.round(scipy.linalg.norm(X - X_k), 3) * np.linalg.matrix_rank(X_k))

7279.84


## Задание 5 ★★☆

Найдите тангенс угла наклона прямой, такой что максимальное расстояние от точек $X$ до прямой минимально. Cчитайте, что прямая проходит через начало координат.

In [3]:
from sklearn.datasets import load_breast_cancer

data = load_breast_cancer()
X = data.data[:, :2]

In [4]:
from numpy.linalg import inv
x = np.column_stack( (np.zeros(X.shape[0]), X[:, 0]))
y = X[:, 1]
w = inv(x.T @ x) @ x.T @ y
w.shape

LinAlgError: Singular matrix

In [5]:
x = X[:, 0]
y = X[:, 1]
w = x.T @ y / (x.T @ x)
print(w)
y_ = w * x - y
print( y_ @ y_ )
y_ = w * 0.9 * x - y
print( y_ @ y_ )

1.3086742363117636
15657.934636886202
17723.624261517354


In [8]:
from sklearn.linear_model import LinearRegression
lin_reg = LinearRegression()
lin_reg.fit(x.reshape(-1, 1), y)
print( f"{lin_reg.intercept_} {lin_reg.coef_}")

13.70697015982554 [0.39516975]


In [9]:
lin_reg = LinearRegression(fit_intercept=False)
lin_reg.fit(x.reshape(-1, 1), y)
print( f"{lin_reg.intercept_} {lin_reg.coef_}")

0.0 [1.30867424]


In [68]:
def function_5(points):
    x = X[:, 0]
    y = X[:, 1]
    w = x.T @ y / (x.T @ x)
    return w

Значение для формы

In [69]:
print(round(function_5(X), 3))

1.309
